# https://github.com/actions/virtual-environments/blob/main/docs/create-image-and-azure-resources.md

# Install Choco
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

# Check Choco install
choco -?

# Install Packer
choco install packer

# Install Git
choco install git -params '"/GitAndUnixToolsOnPath"'

# Install Azure Az PowerShell Modules
Install-Module -Name Az -Repository PSGallery -Force

# Install Azure CLI
Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi; Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet'; rm .\AzureCLI.msi

# Clone virtual-environments repo
Set-Location c:\
git clone https://github.com/actions/virtual-environments.git

# Generate image VHD
Set-Location C:\virtual-environments
Import-Module .\helpers\GenerateResourcesAndImage.ps1

<#

Subscription ID:        The Azure subscription Id where resources will be created.
    0805677a-fb2c-426d-aacf-2f55ec066d53
Resource Group Name:    The Azure resource group name where the Azure resources will be created.
    "rgPackerBuild" <<<<<<< ** DO NOT USE PROD RESOURCE GROUP **
Image Gen Repo Root:    The root path of the image generation repository source.
    "C:\virtual-environments"
Image Type:             The type of the image being generated. Valid options are: {"Windows2016", "Windows2019", "Windows2022", "Ubuntu1804", "Ubuntu2004"}.
   "Windows2022"
Azure Location:         The location of the resources being created in Azure. For example "East US".
    "East US"
Tags:                   A hashtable containing any tags to be assigned to the 
    @{dept="devops";env="prod"}

Example:
GenerateResourcesAndImage -SubscriptionId {0805677a-fb2c-426d-aacf-2f55ec066d53} -ResourceGroupName "rgPackerBuild" -ImageGenerationRepositoryRoot "$pwd" -ImageType "Windows2022" -AzureLocation "East US"

#>

GenerateResourcesAndImage -SubscriptionId {0805677a-fb2c-426d-aacf-2f55ec066d53} -ResourceGroupName "rgPackerBuild" -ImageGenerationRepositoryRoot "$pwd" -ImageType "Windows2022" -AzureLocation "East US"

# Prep VHD to create Azure VM
Set-Location C:\virtual-environments
Import-Module .\helpers\MCP_CreateAzureVMFromPackerTemplate.ps1

<#

Subscription ID:        The Azure subscription Id where resources will be created.
    0805677a-fb2c-426d-aacf-2f55ec066d53
Resource Group Name:    The Azure resource group name where the Azure resources will be created.
    "rgEastUS"
Template File:          The path for the json template generated by packer during image generation locally.
    "C:\virtual-environments"
Virtual Machine Name:   The name of the virtual machine to be generated.
   "eus-HOSTNAME"
Admin Username:         Username of the local administrator account.
    "jagermeister"
Admin Password:         Password for the local administrator account.
    "SomeSecurePassword"    <<< Don't use standard format, change once VM is provisioned.
Azure Location:         The location of the resources being created in Azure. For example "East US".
    "East US"
Subnet ID:              Name of the subnet where the VM's NIC should be attached to.
    "subAppEUs"

Example:
CreateAzureVMFromPackerTemplate -SubscriptionId {0805677a-fb2c-426d-aacf-2f55ec066d53}  -ResourceGroupName {rgEastUS} -TemplateFile "C:\BuildVmImages\temporaryTemplate.json" -VirtualMachineName "testvm1" -AdminUsername "jagermeister" -AdminPassword "SomeSecurePassword1" -AzureLocation "EastUS" -subnetID "subAppEUs"

#>

CreateAzureVMFromPackerTemplate-MCP -SubscriptionId {0805677a-fb2c-426d-aacf-2f55ec066d53}  -ResourceGroupName {rgEastUS} -TemplateFile "C:\virtual-environments\_MCPHS\packer-vmTemplate.768514a3-5903-44ae-aaca-ed8c0c93ea9b.json" -VirtualMachineName "eus-TADOAPP02" -AdminUsername "jagermeister" -AdminPassword "SomeSecurePassword1" -AzureLocation "EastUS" -subnetId "subAppEUs"