Function CreateAzureVMFromPackerTemplate-MCP {
    <#
        .SYNOPSIS
            A helper function to deploy a VM from a generated image.

        .DESCRIPTION
             Creates an Azure VM from a template. Also generates network resources in Azure to make the VM accessible.

        .PARAMETER SubscriptionId
            The Azure subscription Id where resources will be created.

        .PARAMETER ResourceGroupName
            The Azure resource group name where the Azure virtual machine will be created.

        .PARAMETER TemplatFilePath
            The path for the json template generated by packer during image generation locally.

        .PARAMETER VirtualMachineName
            The name of the virtual machine to be generated.

        .PARAMETER AdminUserName
            The administrator username for the virtual machine to be created.

        .PARAMETER AdminPassword
            The administrator password for the virtual machine to be created.

        .PARAMETER AzureLocation
            The location where the Azure virtual machine will be provisioned. Example: "eastus"

        .PARAMETER SubnetId
            The subnet name where the VM's NIC should be placed.

        .EXAMPLE
            CreateAzureVMFromPackerTemplate-MCP -SubscriptionId {0805677a-fb2c-426d-aacf-2f55ec066d53} -ResourceGroupName {rgEastUS} -TemplateFile "C:\BuildVmImages\temporaryTemplate.json" -VirtualMachineName "eus-TADOAPP02" -AdminUsername "jagermeister" -AdminPassword "SomeSecurePassword1" -AzureLocation "eastus" -SubnetId "subAppEUs"
    #>
    param (
        [Parameter(Mandatory = $True)]
        [string] $SubscriptionId,
        [Parameter(Mandatory = $True)]
        [string] $ResourceGroupName,
        [Parameter(Mandatory = $True)]
        [string] $TemplateFilePath,
        [Parameter(Mandatory = $True)]
        [string] $VirtualMachineName,
        [Parameter(Mandatory = $True)]
        [string] $AdminUsername,
        [Parameter(Mandatory = $True)]
        [string] $AdminPassword,
        [Parameter(Mandatory = $True)]
        [string] $AzureLocation,
        [Parameter(Mandatory = $True)]
        [string] $SubnetId
    )

    $vmSize = "Standard_D2as_v4"
    $rand = ( Get-Random -Minimum 100 -Maximum 999 ).ToString('000')
    $hostlower = $VirtualMachineName.ToLower()
    $nicName = $hostlower + $rand    

    Write-Host "`nCreating a network interface controller (NIC)"
    ($nic = az network nic create -g $ResourceGroupName -l $AzureLocation -n $nicName --vnet-name "tomCLOUD" --subnet $subnetId --subscription $subscriptionId -o json)
    $networkId = ($nic | ConvertFrom-Json).NewNIC.id

    pause

    Write-Host "`nCreating the VM"
    az deployment group create -g $ResourceGroupName -n $VirtualMachineName --subscription $subscriptionId --template-file $templateFilePath --parameters vmSize=$vmSize vmName=$VirtualMachineName adminUserName=$AdminUsername adminPassword=$AdminPassword networkInterfaceId=$networkId

    pause

    Write-Host "`nCreated in ${ResourceGroupName}:`n  nic ${nicName}`n  vm ${VirtualMachineName}"
}
